name: Check Semver for Pull Request
on:
  pull_request:
    branches: [master]
    types: [labeled, unlabeled, opened]
jobs:
  verify-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Pull Request Version
        id: pr-version
        run: |
          echo "version=$(jq -r .version package.json)" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          ref: master
      - name: Get Base Version
        id: base-version
        run: |
          echo "version=$(jq -r .version package.json)" >> $GITHUB_ENV
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install semver
      - uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const semver = require("semver")
            const pr_version = "${{steps.pr-version.outputs.version}}"
            const base_version = "${{steps.base-version.outputs.version}}"
            const pr_is_higher = semver.gt(pr_version, base_version)
            if (!pr_is_higher) {
              core.setFailed(`The pr version (${pr_version}) is not greater than the base version (${base_version})`)
            } else {
              core.debug(`Success, the pr version (${pr_version}) is higher than the base version (${base_version}).`)
            }
