name: Check Semver for Pull Request
on:
  pull_request:
    branches: [master]
    types: [labeled, unlabeled, opened]
jobs:
  verify-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rayepps/require-semver-bump@v1
        if: contains(github.event.pull_request.labels.*.name, 'release')
        with:
          file: package.json
          pattern: >
            \\"version\\":\s\\"(.+?)\\"
